### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by kris-singh** [zoq/gym_tcp_api#1]
I am using ubuntu 14.04.
The installation of the server went fine. It was listening on port 4040.
But when running ./example from build directory.
terminate called after throwing an instance of 'boost::system::system_error'
  what():  Connection refused
netstat output:
Aborted (core dumped)
tcp        0      0 0.0.0.0:4040            0.0.0.0:*               LISTEN      6623/beam.smp

**Comment by zoq** [comment]
Hello, do you run your own server instance? If that's the case, can you make sure line 17 in example.cpp matches your settings e.g. instead of ``const std::string host = "kurg.org";`` you can use: ``const std::string host = "127.0.0.1";``. Let me know if that helps.

**Comment by kris-singh** [comment]
@zoq some linking errors while recompiling example cpp. I think needs the libboost mt links which are not present with newest libboost. should i do something like [this](https://askubuntu.com/questions/486006/cannot-find-boost-thread-mt-library).

**Comment by zoq** [comment]
Can you test it with: ``cmake -DBoost_USE_MULTITHREADED=OFF ../``?

**Comment by kris-singh** [comment]
Yes that is not helping. There is still linker error with something like this
  ```undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'```

**Comment by zoq** [comment]
Okay, I thought the error has something to do with boost thread. Anyway, the zlib support isn't necessary, but before I write some code, that checks for the zlib support maybe that also works:

1. Install

```
apt-get install zlib1g
apt-get install zlib1g-dev
```

2. Add -lz in CMakeLists.txt in line 7 and 8
```
SET(CMAKE_CXX_FLAGS "-std=c++11 -O3 -fPIC -ffast-math -lz ${CMAKE_CXX_FLAGS}")
SET(CMAKE_C_FLAGS "-std=c99 -O3 -lz ${CMAKE_C_FLAGS}")
```

**Comment by kris-singh** [comment]
@zoq This finally works. I have the basic version for gym that did not have the space invader enviorment. Changed it to Cartpole env it renders fine.

**Comment by zoq** [comment]
Great, I'll update the CMakeList.txt accordingly.
