### ISSUE TITLE
Maintenance work for compatibility with the OpenAI gym's latest version.

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [zoq/gym_tcp_api#12]
This is related to #11. The OpenAI gym's interface has been changed since 0.9.5 version. So we have to adjust the code to be compatible with the latest version. You can find the previous and latest `gym` code in the [GitHub](https://github.com/openai/gym). Actually, I thought I can work on this, but unfortunately I can't find time to do. So, if there is anyone who wants to contribute to this, please feel free. :)

**Comment by MuLx10** [comment]
Hey, @KimSangYeon-DGU and @zoq  I want to contribute. I see that the Monitor doesn't seem to work for gym>0.9.5.

**Comment by KimSangYeon-DGU** [comment]
@MuLx10, Sure, go ahead. :)

**Comment by MuLx10** [comment]
@zoq @KimSangYeon-DGU I suppose that the newer gym versions are kind of python3 supporting.
`    env =gym.make(en)
  File "/usr/lib/python2.7/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/usr/lib/python2.7/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/usr/lib/python2.7/site-packages/gym/envs/registration.py", line 87, in make
    env = cls(**_kwargs)
  File "/usr/lib/python2.7/site-packages/gym/envs/toy_text/taxi.py", line 104, in __init__
    discrete.DiscreteEnv.__init__(self, nS, nA, P, isd)
  File "/usr/lib/python2.7/site-packages/gym/envs/toy_text/discrete.py", line 38, in __init__
    self.action_space = spaces.Discrete(self.nA)
  File "/usr/lib/python2.7/site-packages/gym/spaces/discrete.py", line 15, in __init__
    super().__init__((), np.int64)
TypeError: super() takes at least 1 argument (0 given)`


The constructor issue is inherent trouble of Python2 code when executed using Python3. 
Also the higher versions of gym is written in Python3. 
Should we move to Python3?

**Comment by KimSangYeon-DGU** [comment]
@MuLx10, Right, the problem was resolved, just by running the server in default python3.

1. Edit `from gym.wrappers.monitoring import Monitor` to `from gym.wrappers import Monitor` in `priv/worker.py`.
2. Just run the server in python3.

After checking it, feel free to make a pull request. Thanks for taking time to do. :)

p.s. It would be a good idea to make a note indicating that the version of python should be 3 for compatibility with the latest `gym` for users.

**Comment by MuLx10** [comment]
@KimSangYeon-DGU @zoq I have made the necessary changes. Please review it (#13).
Thank You

**Comment by KimSangYeon-DGU** [comment]
Thanks again!! @MuLx10
