### ISSUE TITLE
mix deps.get error 

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [zoq/gym_tcp_api#5]
Hi, I want to use openai gym, but as you know, It provides only python version.

I have searched method to run other languages, more specifically c++ and found this repository.

First of all, thank you for making this.

However, in the middle of installing this program, an error did occur.

I typed mix deps.get in gym_tcp_api directory but below error message did occur.

```
Failed to fetch record for 'hexpm/poolboy' from registry (using cache)
{:failed_connect, [{:to_address, {'localhost', 4001}}, {:inet, [:inet], :econnrefused}]}
** (Mix) Unknown package poolboy in lockfile
```

**Comment by zoq** [comment]
This might be a caching issue, could you  remove the cache and try again: ``rm "~/.hex/cache.ets"``

**Comment by KimSangYeon-DGU** [comment]
@zoq 
Oh.. thank you for reply, after I removed "~/.hex/cache.ets", the required dependencies were installed correctly!!! Thank you so much
